#spring.security.user.name=telusko
#spring.security.user.password=1234
server.port=8081

# PostgreSQL  Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=Abhishek@007
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.session.cookie.same-site=strict
